apiVersion: v1
kind: Service
metadata:
  name: {{ include "samplenginx.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "samplenginx.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    {{- include "samplenginx.selectorLabels" . | nindent 4 }}
